insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Ivan', 'Khihlyho', 24, 89992313322);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Vlad', 'Pypko', 17, 89992845321);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Valay', 'Taranov', 20, 89992223341);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Olia', 'Sorokina', 33, 89992313322);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Vladimir', 'Koren', 26, 89992313322);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Katia', 'Zilko', 24, 89114321111);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Alex', 'Lipko', 29, 89992313322);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Sasha', 'Gipko', 22, 89994325411);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Kostia', 'Vilcova', 14, 89992312598);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Kirall', 'Ivanov', 18, 89992313322);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Oleg', 'Sidorov', 40, 89996549999);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Stas', 'Azimov', 31, 89118769889);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Vova', 'Stypin', 20, 89118767779);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Roma', 'Kislin', 50, 89118763333);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Alexey', 'Ki', 30, 89118763223);
insert into i.CUSTOMERS (name, surname, age, phone_number) values ('Alexey', 'Kim', 33, 89118553223);

insert into i.ORDERS (customer_id, product_name, amount) values (1, 'milk', 1);
insert into i.ORDERS (customer_id, product_name, amount) values (3, 'meat', 3);
insert into i.ORDERS (customer_id, product_name, amount) values (4, 'meat', 2);
insert into i.ORDERS (customer_id, product_name, amount) values (6, 'fish', 5);
insert into i.ORDERS (customer_id, product_name, amount) values (8, 'milk', 1);
insert into i.ORDERS (customer_id, product_name, amount) values (9, 'fish', 2);
insert into i.ORDERS (customer_id, product_name, amount) values (12, 'meat', 1);
insert into i.ORDERS (customer_id, product_name, amount) values (13, 'soda', 2);
insert into i.ORDERS (customer_id, product_name, amount) values (14, 'meat', 7);
insert into i.ORDERS (customer_id, product_name, amount) values (15, 'fish', 4);
insert into i.ORDERS (customer_id, product_name, amount) values (2, 'soda', 2);
insert into i.ORDERS (customer_id, product_name, amount) values (15, 'soda', 7);
